version: 2
updates:
- package-ecosystem: pip
  directory: "/Medium"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/dev.to"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/gitblog"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/Telegram"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
